name: food_ordering_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  intl: ^0.19.0
  flutter_clip_shadow: ^1.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.8
  another_flushbar: ^1.12.30
  google_generative_ai: ^0.2.1
  chat_bubbles: ^1.5.0
  flutter_spinkit: ^5.2.0
  image_picker: ^1.1.2
  csv: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/food/
    - assets/images/real/
    - assets/images/virtual/
    - assets/data/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.ttf
        - asset: assets/fonts/Metropolis-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Metropolis-Bold.ttf
          weight: 700
        - asset: assets/fonts/Metropolis-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Metropolis-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Metropolis-ExtraBoldItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Metropolis-Medium.ttf
          weight: 500
        - asset: assets/fonts/Metropolis-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Metropolis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Metropolis-SemiBoldItalic.ttf
          weight: 600
          style: italic